### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by NewtOliver** [idiap/gafar#1]
Thank you for your excellent work! I encountered the following error while executing the training instructions. Could you please advise on how to resolve it?
![image](https://github.com/idiap/gafar/assets/45253712/78129325-f7b7-4321-bb85-1bef66e37836)

**Comment by otroshi** [comment]
Thanks for your interest in our work!

You can install `bob.extension v7.0.5` to solve this issue: `pip install bob.extension==7.0.5`

If it still fails with `bob.extension v7.0.5`, make sure that the `~/.bobrc` file is deleted.

**Comment by wynsmile** [comment]
Hello, I would like to ask why there is a big gap between the SAR of my evaluation results and the one you give. I have tried the evaluation of each model, and the following are some examples of my evaluation results:
For ElasticFace-ElasticFace:
FMR: 0.01 threshold: -0.7965051331730502 TMR: 0.9683333333333334, SAR: 0.631590181430096
FMR: 0.001 threshold: -0.7072022021466418 TMR: 0.947, SAR: 0.32689434364994663
Did you have the same problem? @NewtOliver
