### ISSUE TITLE
train.pyproblem

### ISSUE THREAD

**Issue by Lier-Accuser** [idiap/gafar#2]
Hello, may I ask why this error occurred while running the train.py file

************
 NOTE: The torch device is: cuda
Traceback (most recent call last):
  File "/mnt/data/hangyicheng/face-test/bob.paper.iccv2023_face_ti/train.py", line 58, in <module>
    EG3D = pickle.load(f)['G_ema']
ModuleNotFoundError: No module named 'torch_utils.persistence'

**Comment by otroshi** [comment]
The error is for loading the EG3D model and is raised because the modules are not imported properly. To fix it, you need to make sure that `--path_eg3d_repo`  refers to the `eg3d` folder within the repository of EG3D.

**Comment by Lier-Accuser** [comment]
Thank you for your reply, the problem has been solved succseefully!

**Comment by otroshi** [comment]
The issue is solved in https://github.com/idiap/gafar/commit/8329bb3a3050035fde46f3b7f4a21f545482edd0 such that `--path_eg3d_repo` refers to the root of EG3D repository.
