### ISSUE TITLE
the trained face reconstruction model

### ISSUE THREAD

**Issue by wynsmile** [idiap/gafar#4]
Thank you for your great work. Can you give us the trained face reconstruction model?

**Comment by wynsmile** [comment]
Thank you very much and look forward to your reply.

**Comment by otroshi** [comment]
Thanks for your interest in our work. [Checkpoints](https://www.idiap.ch/paper/gafar/static/files/checkpoints.zip) of trained models of the mapping network for whitebox and blackbox attacks are uploaded and available in the [project page](https://www.idiap.ch/paper/gafar/).
