### ISSUE TITLE
SAR of evaluation

### ISSUE THREAD

**Issue by wynsmile** [idiap/gafar#7]
Dear author, thank you for your excellent work. I would like to ask why there is a big gap between the SAR of my evaluation results and the one you give. I have tried the evaluation of each model, and the following are some examples of my evaluation results:
For ElasticFace-ElasticFace:
 FMR: 0.01 	 threshold: -0.7965051331730502 	 TMR: 0.9683333333333334, SAR: 0.631590181430096
FMR: 0.001 	 threshold: -0.7072022021466418 	 TMR: 0.947, SAR: 0.32689434364994663

**Comment by wynsmile** [comment]
Through the help, I know that the model selected by EG3D is ffhqrebalanced512-128.pkl. The problem has been solved, thank you very much.

**Comment by otroshi** [comment]
Thanks @wynsmile for raising the issue. Indeed, there was a typo in the name of EG3D pickle file which is now fixed. You need to use `ffhqrebalanced512-128.pkl` [checkpoint](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/eg3d/files) for EG3D.
